# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

includes:
  docker: ./tasks/DockerTasks.yml
  dockle: ./tasks/DockleTasks.yml
  git: ./tasks/GitTasks.yml
  hadolint: ./tasks/HadolintTasks.yml
  markdownlint: ./tasks/MarkdownlintTasks.yml
  trivy: ./tasks/TrivyTasks.yml
  yamllint: ./tasks/YamllintTasks.yml

vars:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REPOSITORY: ffurrer2/yamllint
  DOCKER_TAG: {sh: 'sed -n "s/^ARG YAMLLINT_VERSION=\([0-9]*\.[0-9]*\.[0-9]*\)/\1/p" Dockerfile'}
  IMAGE_NAME: '{{.DOCKER_REGISTRY}}/{{.DOCKER_REPOSITORY}}:{{.DOCKER_TAG}}'

tasks:
  default:
    cmds:
    - task --list
    silent: true

  lint:
    desc: Run all linters
    cmds:
    - task: dockle:lint
      vars:
        IMAGE_NAME: '{{.IMAGE_NAME}}'
    - task: hadolint:lint
    - task: markdownlint:lint
    - task: trivy:image
      vars:
        IMAGE_NAME: '{{.IMAGE_NAME}}'
    - task: yamllint:lint
    silent: true
