# SPDX-License-Identifier: MIT
name: Lint

on:
  push:
    branches:
    - master
    - feature/**
    paths:
    - '**.yaml'
    - '**.yml'
    - '.yamllint'
    - 'Dockerfile'
    - 'hooks/*'

jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Shellcheck
      uses: docker://koalaman/shellcheck:latest
      with:
        entrypoint: /bin/shellcheck
        args: '--check-sourced --color=auto --format=tty --enable=all --shell=bash --severity=style --source-path=./ hooks/build hooks/post_push'

  yamllint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: yamllint
      uses: docker://ffurrer/yamllint:latest
      with:
        args: '--format auto --strict .'

  hadolint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: hadolint
      uses: docker://hadolint/hadolint:latest
      with:
        args: 'hadolint --format tty Dockerfile'
